In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('https://raw.githubusercontent.com/Gaelim/YT_bike_share/refs/heads/main/bike_share_yr_0.csv')
df1.head()

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  1/1/2021       1   0     1   0        0        6           0           1   
1  1/1/2021       1   0     1   1        0        6           0           1   
2  1/1/2021       1   0     1   2        0        6           0           1   
3  1/1/2021       1   0     1   3        0        6           0           1   
4  1/1/2021       1   0     1   4        0        6           0           1   

   temp   atemp   hum  windspeed rider_type  riders  
0  0.24  0.2879  0.81        0.0     casual       3  
1  0.22  0.2727  0.80        0.0     casual       8  
2  0.22  0.2727  0.80        0.0     casual       5  
3  0.24  0.2879  0.75        0.0     casual       3  
4  0.24  0.2879  0.75        0.0     casual       0

In [3]:
df2 = pd.read_csv('https://raw.githubusercontent.com/Gaelim/YT_bike_share/refs/heads/main/bike_share_yr_1.csv')
df2.head()

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  1/1/2022       1   1     1   0        0        0           0           1   
1  1/1/2022       1   1     1   1        0        0           0           1   
2  1/1/2022       1   1     1   2        0        0           0           1   
3  1/1/2022       1   1     1   3        0        0           0           1   
4  1/1/2022       1   1     1   4        0        0           0           1   

   temp   atemp   hum  windspeed rider_type  riders  
0  0.36  0.3788  0.66     0.0000     casual       5  
1  0.36  0.3485  0.66     0.1343     casual      15  
2  0.32  0.3485  0.76     0.0000     casual      16  
3  0.30  0.3333  0.81     0.0000     casual      11  
4  0.28  0.3030  0.81     0.0896     casual       0

In [4]:
df1.columns == df2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [5]:
df1.yr.unique()

array([0], dtype=int64)

In [6]:
df2.yr.unique()

array([1], dtype=int64)

In [7]:
df1.shape, df2.shape

((17290, 15), (17468, 15))

In [11]:
df = pd.concat([df1, df2], axis = 0)
df.head()

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  1/1/2021       1   0     1   0        0        6           0           1   
1  1/1/2021       1   0     1   1        0        6           0           1   
2  1/1/2021       1   0     1   2        0        6           0           1   
3  1/1/2021       1   0     1   3        0        6           0           1   
4  1/1/2021       1   0     1   4        0        6           0           1   

   temp   atemp   hum  windspeed rider_type  riders  
0  0.24  0.2879  0.81        0.0     casual       3  
1  0.22  0.2727  0.80        0.0     casual       8  
2  0.22  0.2727  0.80        0.0     casual       5  
3  0.24  0.2879  0.75        0.0     casual       3  
4  0.24  0.2879  0.75        0.0     casual       0

In [12]:
df.shape

(34758, 15)

In [13]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  20/4/2022       2   1     4   0        0        5           1           1   
1  10/6/2022       2   1     6   6        0        0           0           1   
2   8/1/2021       1   0     1   0        0        6           0           2   
3  31/7/2022       3   1     7  20        0        2           1           3   
4   1/3/2021       1   0     3  22        0        2           1           1   

   temp   atemp   hum  windspeed  rider_type  riders  
0  0.48  0.4697  0.67     0.1045  registered      59  
1  0.62  0.5909  0.73     0.0000      casual       3  
2  0.18  0.1970  0.51     0.1642      casual       1  
3  0.70  0.6515  0.70     0.1940  registered     397  
4  0.24  0.2727  0.62     0.1045      casual       3

In [14]:
df.yr.value_counts(normalize = True)

yr
1    0.502561
0    0.497439
Name: proportion, dtype: float64

In [15]:
# df.to_csv('bike_data.csv', index = False)